import type { RunClient } from 'apify-client';

import { ExtRunClient } from '../clients/run-client.js';
import { RunRequestGuard } from '../run-request-guard.js';
import { RunScheduler } from '../run-scheduler.js';
import type { TrackedRuns } from '../run-tracker.js';
import { RunTracker } from '../run-tracker.js';
import type { ExtendedActorRun, RunInfo } from '../types.js';
import { mergeDictionaries } from '../utils/dictionaries.js';
import { Outcome } from '../utils/outcome.js';
import type { OrchestratorContext } from './orchestrator-context.js';

/**
 * Represents the outcome of searching internally for an existing Run by name.
 * We may be waiting for the Run to start, or we may have tracked information about the Run.
 */
export class RunSearchOutcome extends Outcome<{
    promise: () => Promise<ExtendedActorRun>;
    runInfo: RunInfo;
    notFound: true;
}> {}

/**
 * Represents the context available to an Apify Client and other derived clients.
 */
export interface ClientContext extends OrchestratorContext {
    readonly runTracker: RunTracker;
    readonly runScheduler: RunScheduler;
    /**
     * Keeps track of requests IDs generated by this process for this client; gets reset on resurrection.
     */
    readonly runRequestGuard: RunRequestGuard;

    searchExistingRun(requestId: string): RunSearchOutcome;
    extendRunClient(requestId: string, runClient: RunClient): ExtRunClient;
}

export function generateClientContext(
    orchestratorContext: OrchestratorContext,
    trackedRuns: TrackedRuns,
): ClientContext {
    const runTracker = new RunTracker(orchestratorContext, trackedRuns);
    const runRequestGuard = new RunRequestGuard();

    const runScheduler = new RunScheduler(orchestratorContext, {
        runRequestAdapter: (request) => ({
            ...request,
            input: mergeDictionaries(orchestratorContext.options.fixedInput, request.input),
        }),
        onRunStarted: (requestId, run) => runTracker.updateRun(requestId, run),
    });

    return {
        ...orchestratorContext,
        runTracker,
        runScheduler,
        runRequestGuard,

        searchExistingRun(requestId: string): RunSearchOutcome {
            // First, check if the Run is currently waiting to start.
            const runPromise = this.runScheduler.findRunStartRequest(requestId);
            if (runPromise) return new RunSearchOutcome({ promise: runPromise });

            // Then, check if there is any info about the Run in the tracker.
            const runInfo = this.runTracker.findRunByRequestId(requestId);
            if (runInfo) return new RunSearchOutcome({ runInfo });

            // Otherwise, a run with this name does not exist.
            return new RunSearchOutcome({ notFound: true });
        },

        extendRunClient(requestId: string, runClient: RunClient): ExtRunClient {
            return new ExtRunClient(
                this,
                // Track every Run update.
                { requestId, onUpdate: (run) => this.runTracker.updateRun(requestId, run) },
                runClient,
            );
        },
    };
}
