name: CI

on:
    pull_request:

permissions:
    # Recommended: sets the permissions given to the GITHUB_TOKEN for this workflow
    contents: read

jobs:
    ci:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20, 22, 24, 26]

        steps:
            - name: Checkout code
              uses: actions/checkout@v7
              with:
                  # By default, actions/checkout writes the GITHUB_TOKEN into the local .git/config
                  # We don't need to perform any Git operation, so we disable persisting credentials
                  persist-credentials: false

            - name: Setup Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v7
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm ci

            - name: Checking lint
              run: npm run lint

            - name: Checking formatting
              run: npm run format:check

            - name: Building the project
              run: npm run build

            - name: Running tests
              run: npm test
